version: "3"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - ENV=production
      - ENV_FILE=.env
      - PORT=443
      - MQTT_HOST=coffeetalk.hermannm.dev
      - MQTT_PORT=1882
    ports:
      - 443:443
  mqtt:
    container_name: mqtt
    build:
      context: ./mqtt
      dockerfile: Dockerfile
    environment:
      - ENV=production
      - SOCKET_PORT=1882
      - TCP_PORT=1883
    ports:
      - 1882:1882
      - 1883:1883
