version: "3"

services:
  # Container for the CoffeeTalk web server.
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      - ENV=production
      - PORT=443
      - WEBRTC_HOST=coffeetalk.hermannm.dev
      - WEBRTC_PORT=8000
      - MQTT_HOST=coffeetalk.hermannm.dev
      - MQTT_PORT=1882
    ports:
      - 443:443

  # Container for the CoffeeTalk WebRTC signaling server.
  webrtc:
    container_name: webrtc
    build:
      context: ./webrtc
      dockerfile: Dockerfile
    environment:
      - ENV=production
      - PORT=8000
    ports:
      - 8000:8000

  # Container for the Coffeetalk MQTT quiz server.
  mqtt:
    container_name: mqtt
    build:
      context: ./mqtt
      dockerfile: Dockerfile
    environment:
      - ENV=production
      - SOCKET_PORT=1882
      - TCP_PORT=1883
    ports:
      - 1882:1882
      - 1883:1883
